name: PrimeAssistant
version: ${version}
main: me.optimusprimerdc.primeAssistant.PrimeAssistant
api-version: '1.21'
authors: [ OptimusPrimeRDC ]
description: Personal Assistant for HuhnSMP
website: https://github.com/ConsoleGods/PrimeAssistant
depend:
  - WorldGuard
  - Vault
commands:
  primeassistant:
    description: Main command for PrimeAssistant
    usage: /primeassistant <reload|unban|unmute> [player]
    aliases: [pa]
    permission-message: '&cYou do not have permission to use PrimeAssistant commands.'
  cf:
    description: CoinFlip command
    usage: /cf <player> <amount>

permissions:
  primeassistant.updates:
    default: op
  primeassistant.notify:
    default: op
  primeassistant.chat.notify:
    default: op
  primeassistant.unban:
    default: op
  primeassistant.unmute:
    default: op
  primeassistant.reload:
    default: op
  primeassistant.bypass:
    default: op